package com.example.devicemonitor.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;

import javax.annotation.processing.Generated;
import java.time.Instant;

/**
 * JPA entity representing a monitored network device.
 *
 * <p>Each {@code Device} record corresponds to a single physical or virtual
 * device (server, router, VM, etc.) that the system tracks. Devices are stored
 * in the {@code devices} table and are the central data object of the entire
 * application — every other layer (controller, service, repository) either
 * produces or consumes instances of this class.
 *
 * <p><b>IP uniqueness:</b> Uniqueness of {@code ipAddress} is <em>not</em>
 * enforced at the database-constraint level. Instead, {@code DeviceService}
 * performs the duplicate check before persisting so that it can return a
 * meaningful application-level error rather than a raw SQL constraint
 * violation.
 *
 * <p><b>Initial status:</b> New devices always start in the {@code UNKNOWN}
 * state. The status is updated to {@code ONLINE} or {@code OFFLINE} only after
 * an explicit health-check cycle runs against the device's IP address.
 */
@Entity
@Table(name= "devices")
public class Device {

    /**
     * Auto-incremented primary key generated by the database identity column.
     * Clients never supply this value; it is assigned on first {@code INSERT}.
     */
    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Long id;

    /**
     * Human-readable display name for the device (e.g. "Web Server 01").
     * Must be non-blank; validated by Bean Validation before the entity
     * reaches the persistence layer.
     */
    @NotBlank(message = "Device name is required")
    private String name;

    /**
     * IPv4 (or IPv6) address used to reach the device during health checks.
     * Must be non-blank. Uniqueness across all persisted devices is enforced
     * in {@code DeviceService.registerDevice} rather than via a DB constraint.
     */
    @NotBlank(message = "IP address is required")
    private String ipAddress;

    /**
     * Current reachability state of the device.
     * Stored as its enum name string (e.g. "ONLINE") so the column value
     * remains human-readable in the database and survives enum reordering.
     *
     * @see DeviceStatus
     */
    @Enumerated (EnumType.STRING)
    private DeviceStatus status;

    /**
     * UTC timestamp of the most recent moment the device was observed to be
     * reachable. Updated by {@code DeviceService} after each successful health
     * check. {@code Instant} is used (rather than {@code LocalDateTime}) to
     * keep all timestamps timezone-agnostic at the data layer.
     */
    private Instant lastSeenAt;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * No-arg constructor required by the JPA specification.
     * Should not be used directly in application code; use the
     * convenience constructor instead.
     */
    public Device() {
    }

    /**
     * Creates a new device with safe initial defaults.
     *
     * <p>Status is always set to {@link DeviceStatus#UNKNOWN} because the
     * device has not yet been health-checked. {@code lastSeenAt} is set to
     * "now" as a reasonable sentinel — it will be overwritten on the first
     * successful ping.
     *
     * @param name      human-readable label for the device; must not be blank
     * @param ipAddress network address used for health checks; must not be blank
     */
    public Device(String name, String ipAddress){
        this.name = name;
        this.ipAddress = ipAddress;
        // New devices begin as UNKNOWN because connectivity has not been verified yet.
        this.status = DeviceStatus.UNKNOWN;
        // Capture creation time as a baseline for lastSeenAt before any health check runs.
        this.lastSeenAt = Instant.now();
    }

    // -------------------------------------------------------------------------
    // Getters and Setters
    // -------------------------------------------------------------------------

    /** Returns the database-assigned primary key, or {@code null} before first persist. */
    public Long getId() { return id; }

    /** Sets the primary key — typically called only by JPA or test fixtures. */
    public void setId(Long id) { this.id = id; }

    /** Returns the device's display name. */
    public String getName() { return name; }

    /** Updates the device's display name. */
    public void setName(String name) { this.name = name; }

    /** Returns the IP address used for reachability checks. */
    public String getIpAddress() { return ipAddress; }

    /** Updates the IP address. Callers must ensure the new address is unique
     *  across all devices (that check lives in {@code DeviceService}). */
    public void setIpAddress(String ipAddress) { this.ipAddress = ipAddress; }

    /** Returns the current reachability status of the device. */
    public DeviceStatus getStatus() { return status; }

    /** Overwrites the current status. Normally called by the health-check logic
     *  in {@code DeviceService} after a ping attempt resolves. */
    public void setStatus(DeviceStatus status) { this.status = status; }

    /** Returns the UTC instant at which the device was last seen reachable. */
    public Instant getLastSeenAt() { return lastSeenAt; }

    /** Updates the last-seen timestamp. Called after a successful health check. */
    public void setLastSeenAt(Instant lastSeenAt) { this.lastSeenAt = lastSeenAt; }

}
